# Generated by Django 4.2.7 on 2023-12-08 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile_date_monifide'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_monifide',
            new_name='date_monified',
        ),
    ]
