# Generated by Django 4.2.7 on 2023-12-12 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
