# Generated by Django 4.2.7 on 2023-12-26 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_creted_at_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
