# Generated by Django 4.2.7 on 2023-12-26 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_image',
            new_name='profile_image',
        ),
    ]
