# Generated by Django 4.2.7 on 2024-01-04 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile_facebook_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='linkidin_link',
            new_name='linkedin_link',
        ),
    ]
