# Generated by Django 4.2.7 on 2024-01-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_rename_linkidin_link_profile_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
