# Generated by Django 4.2.7 on 2024-01-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_profile_profile_image_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
