# Generated by Django 4.2.7 on 2024-01-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_post_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='post_image',
            new_name='profile_image',
        ),
    ]
