# Generated by Django 4.2.7 on 2024-02-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_post_post_image_remove_profile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image_url',
            field=models.URLField(null=True),
        ),
    ]
